--CREATE TABLE Usuarios (
--	ID INT PRIMARY KEY IDENTITY,
--	NOMBRE VARCHAR(50) NOT NULL UNIQUE,
--	CLAVE VARCHAR(50) NOT NULL
--)

--CREATE TABLE Clientes (
--	ID INT PRIMARY KEY IDENTITY,
--	NOMBRE VARCHAR(50) NOT NULL,
--	DNI INT NOT NULL UNIQUE
--)

--CREATE TABLE Especies (
--	ID INT PRIMARY KEY IDENTITY,
--	NOMBRE VARCHAR(50) NOT NULL,
--	EDAD_MADUREZ INT,
--	PESO_PROMEDIO DECIMAL(10, 2)
--)

--CREATE TABLE Animales (
--	ID INT PRIMARY KEY IDENTITY,
--	NOMBRE VARCHAR(50) NOT NULL,
--	EDAD INT,
--	PESO DECIMAL(10, 2),
--	CLIENTE_ID INT FOREIGN KEY REFERENCES Clientes(id),
--	ESPECIE_ID INT FOREIGN KEY REFERENCES Especies(id)
--)



SELECT * FROM Usuarios 
SELECT * FROM Clientes 
SELECT * FROM Especies 
SELECT * FROM Animales 

--INSERT INTO Clientes VALUES ('C1',123456789)
--INSERT INTO Especies VALUES ('PERRO',3,6.5)
--INSERT INTO Especies VALUES ('GATO',1,2)
--INSERT INTO Animales VALUES ('TOGA',10,5,1,2)


